# Generated by Django 4.2.29 on 2026-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1051_backfill_holdout_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportedasset",
            name="data_last_refresh",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportedasset",
            name="is_stale",
            field=models.BooleanField(default=False),
        ),
    ]
